runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

env_variables:
  DATABASE_URI: YOUR_DATABASE_URI
  GOOGLE_CLIENT_ID: YOUR_GOOGLE_CLIENT_ID
  GOOGLE_CLIENT_SECRET: YOUR_GOOGLE_CLIENT_SECRET
  GOOGLE_APPLICATION_CREDENTIALS: YOUR_GOOGLE_APPLICATION_CREDENTIALS
  GOOGLE_PROJECT: YOUR_GOOGLE_PROJECT
  GOOGLE_BUCKET: YOUR_GOOGLE_BUCKET
  GOOGLE_DISCOVERY_URL: YOUR_GOOGLE_DISCOVERY_URL
  FACEBOOK_CLIENT_ID: YOUR_FACEBOOK_CLIENT_ID
  FACEBOOK_CLIENT_SECRET: YOUR_FACEBOOK_CLIENT_SECRET
  FACEBOOK_AUTHORIZE_URL: YOUR_FACEBOOK_AUTHORIZE_URL
  FACEBOOK_ACCESS_TOKEN_URL: YOUR_FACEBOOK_ACCESS_TOKEN_URL
  FACEBOOK_USER_INFO_URL: YOUR_FACEBOOK_USER_INFO_URL
  CONFIG_MODE: 'config.Prod'
