runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

env_variables:
  DATABASE_URI: YOUR_DATABASE_URI
  GOOGLE_CLIENT_ID: YOUR_GOOGLE_CLIENT_ID
  GOOGLE_CLIENT_SECRET: YOUR_GOOGLE_CLIENT_SECRET
  GOOGLE_PROJECT: YOUR_GOOGLE_PROJECT
  GOOGLE_BUCKET: YOUR_GOOGLE_BUCKET
  FACEBOOK_CLIENT_ID: YOUR_FACEBOOK_CLIENT_ID
  FACEBOOK_CLIENT_SECRET: YOUR_FACEBOOK_CLIENT_SECRET
  GOOGLE_APPLICATION_CREDENTIALS: .credentials/crm-service-storage-key.json
  GOOGLE_DISCOVERY_URL: https://accounts.google.com/.well-known/openid-configuration
  FACEBOOK_ACCESS_TOKEN_URL: https://graph.facebook.com/oauth/access_token
  FACEBOOK_AUTHORIZE_URL: https://graph.facebook.com/oauth/authorize
  FACEBOOK_USER_INFO_URL: https://graph.facebook.com/me?fields=email
  CONFIG_MODE: 'config.Prod'
