name: CI

on:
  push:
    branches:
      - feature/cicd


jobs:
  build:

    runs-on: ubuntu-latest
    # env:
    #   FLASK_APP: main
    #   FLASK_ENV: development
    #   CONFIG_MODE: 'config.Test'
    #   PYTHONUNBUFFERED: 1
    #   GOOGLE_BUCKET_PREFIX: https://storage.googleapis.com/
    #   GOOGLE_DISCOVERY_URL: https://accounts.google.com/.well-known/openid-configuration
    #   FACEBOOK_AUTHORIZE_URL: https://graph.facebook.com/oauth/authorize
    #   FACEBOOK_ACCESS_TOKEN_URL: https://graph.facebook.com/oauth/access_token
    #   FACEBOOK_USER_INFO_URL: https://graph.facebook.com/me?fields=email
    #   GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID}}
    #   GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET}}
    #   FACEBOOK_CLIENT_ID: ${{ secrets.FACEBOOK_CLIENT_ID}}
    #   FACEBOOK_CLIENT_SECRET:  ${{ secrets.FACEBOOK_CLIENT_SECRET}}
    #   GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT}}
    #   GOOGLE_BUCKET: ${{ secrets.GOOGLE_BUCKET}}
    #   GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}
    #   DATABASE_URI: ${{ secrets.DATABASE_URI}}

    steps:
    - uses: actions/checkout@v1
    - name: get variables
      with: # Set the secret as an input
        super_secret: ${{ secrets.GOOGLE_BUCKET }}
      env: # Or as an environment variable
        super_secret: ${{ secrets.GOOGLE_BUCKET }}
      run: echo "AAAA ${super_secret}"
        
    - name: create .env
      run: cp env .env
      working-directory: ./app
    - name: Change variables
      env:
        FLASK_APP: main
        FLASK_ENV: development
        CONFIG_MODE: 'config.Test'
        PYTHONUNBUFFERED: 1
        GOOGLE_BUCKET_PREFIX: https://storage.googleapis.com/
        GOOGLE_DISCOVERY_URL: https://accounts.google.com/.well-known/openid-configuration
        FACEBOOK_AUTHORIZE_URL: https://graph.facebook.com/oauth/authorize
        FACEBOOK_ACCESS_TOKEN_URL: https://graph.facebook.com/oauth/access_token
        FACEBOOK_USER_INFO_URL: https://graph.facebook.com/me?fields=email
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID}}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET}}
        FACEBOOK_CLIENT_ID: ${{ secrets.FACEBOOK_CLIENT_ID}}
        FACEBOOK_CLIENT_SECRET:  ${{ secrets.FACEBOOK_CLIENT_SECRET}}
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT}}
        GOOGLE_BUCKET: ${{ secrets.GOOGLE_BUCKET}}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        DATABASE_URI: ${{ secrets.DATABASE_URI}}
      run: |
        sh """sed -i "s*YOUR_DATABASE_URI*${{ secrets.DATABASE_URI}}*g" /home/runner/work/crm/crm/app/.env"""
        sh """sed -i "s*YOUR_GOOGLE_CLIENT_ID*${GOOGLE_CLIENT_ID}*g" /home/runner/work/crm/crm/app/.env"""
        sh """sed -i "s*YOUR_GOOGLE_CLIENT_SECRET*${GOOGLE_CLIENT_SECRET}*g" /home/runner/work/crm/crm/app/.env"""
        sh """sed -i "s*YOUR_GOOGLE_APPLICATION_CREDENTIALS*.credentials/crm-service-storage-key.json*g" /home/runner/work/crm/crm/app/.env"""
        sh """sed -i "s*YOUR_GOOGLE_PROJECT*${GOOGLE_PROJECT}*g" /home/runner/work/crm/crm/app/.env"""
        sh """sed -i "s*YOUR_GOOGLE_BUCKET*${GOOGLE_BUCKET}*g" /home/runner/work/crm/crm/app/.env"""
        sh """sed -i "s*YOUR_FACEBOOK_CLIENT_ID*${FACEBOOK_CLIENT_ID}*g" /home/runner/work/crm/crm/app/.env"""
        sh """sed -i "s*YOUR_FACEBOOK_CLIENT_SECRET*${FACEBOOK_CLIENT_SECRET}*g" /home/runner/work/crm/crm/app/.env"""
    - name: Build the docker-compose stack
      run: docker-compose -f docker-compose-cicd.yaml up -d
      working-directory: ./development_environment
    - name: Docker info
      run: docker info
    - name: Docker ps
      run: docker ps
    - name: Runnint the tests...
      run: docker exec -i "$(docker-compose -f docker-compose-cicd.yaml ps -q backend)" pipenv run python tests.py
      working-directory: ./development_environment
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Modify app.yml
      run: |
        sh """sed -i "s*YOUR_DATABASE_URI*${env.DATABASE_URI}*g" /home/runner/work/crm/crm/app/app.yaml"""
        sh """sed -i "s*YOUR_GOOGLE_CLIENT_ID*${env.GOOGLE_CLIENT_ID}*g" /home/runner/work/crm/crm/app/app.yaml"""
        sh """sed -i "s*YOUR_GOOGLE_CLIENT_SECRET*${env.GOOGLE_CLIENT_SECRET}*g" /home/runner/work/crm/crm/app/app.yaml"""
        sh """sed -i "s*YOUR_GOOGLE_APPLICATION_CREDENTIALS*.credentials/crm-service-storage-key.json*g" /home/runner/work/crm/crm/app/app.yaml"""
        sh """sed -i "s*YOUR_GOOGLE_PROJECT*${env.GOOGLE_PROJECT}*g" /home/runner/work/crm/crm/app/app.yaml"""
        sh """sed -i "s*YOUR_GOOGLE_BUCKET*${env.GOOGLE_BUCKET}*g" /home/runner/work/crm/crm/app/app.yaml"""
        sh """sed -i "s*YOUR_GOOGLE_DISCOVERY_URL*${env.GOOGLE_DISCOVERY_URL}*g" /home/runner/work/crm/crm/app/app.yaml"""
        sh """sed -i "s*YOUR_FACEBOOK_CLIENT_ID*${env.FACEBOOK_CLIENT_ID}*g" /home/runner/work/crm/crm/app/app.yaml"""
        sh """sed -i "s*YOUR_FACEBOOK_CLIENT_SECRET*${env.FACEBOOK_CLIENT_SECRET}*g" /home/runner/work/crm/crm/app/app.yaml"""
        sh """sed -i "s*YOUR_FACEBOOK_AUTHORIZE_URL*${env.FACEBOOK_AUTHORIZE_URL}*g" /home/runner/work/crm/crm/app/app.yaml"""
        sh """sed -i "s*YOUR_FACEBOOK_ACCESS_TOKEN_URL*${env.FACEBOOK_ACCESS_TOKEN_URL}*g" /home/runner/work/crm/crm/app/app.yaml"""
        sh """sed -i "s*YOUR_FACEBOOK_USER_INFO_URL*${env.FACEBOOK_USER_INFO_URL}*g" /home/runner/work/crm/crm/app/app.yaml"""
        sh "cat /home/runner/work/crm/crm/app/app.yaml"
        
        echo $APPLICATION_CREDENTIALS > .credentials/crm-service-storage-key.json
      working-directory: ./app



