name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  build:

    runs-on: ubuntu-latest
    services:
      db_test:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: 'test_db'
          MYSQL_USER: 'user'
          MYSQL_PASSWORD: 'password'
        ports:
        - '3307:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      FLASK_APP: main
      FLASK_ENV: development
      CONFIG_MODE: 'config.Test'
      PYTHONUNBUFFERED: 1
      GOOGLE_BUCKET_PREFIX: https://storage.googleapis.com/
      GOOGLE_DISCOVERY_URL: https://accounts.google.com/.well-known/openid-configuration
      FACEBOOK_AUTHORIZE_URL: https://graph.facebook.com/oauth/authorize
      FACEBOOK_ACCESS_TOKEN_URL: https://graph.facebook.com/oauth/access_token
      FACEBOOK_USER_INFO_URL: https://graph.facebook.com/me?fields=email
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID}}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET}}
      FACEBOOK_CLIENT_ID: ${{ secrets.FACEBOOK_CLIENT_ID}}
      FACEBOOK_CLIENT_SECRET:  ${{ secrets.FACEBOOK_CLIENT_SECRET}}
      GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT}}
      GOOGLE_BUCKET: ${{ secrets.GOOGLE_BUCKET}}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}
      DATABASE_URI: ${{ secrets.DATABASE_URI}}
      DATABASE_TEST_URI: 'mysql://root:password@127.0.0.1:3307/test_db'

    steps:
    - name: Retreiving the repo
      uses: actions/checkout@v1

    - name: Set up Python 
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Install system dependencies
      run: |
        sudo apt-get install libmysqlclient-dev
        sudo apt-get install python-dev

    - name: create .env file
      run: cp env .env
      working-directory: ./app

    - name: Change variables in .env
      run: |
        sh ../deployment_automation/replace_variables.sh .env
      working-directory: ./app

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
      working-directory: ./app

    - name: Setting up GCloud Auth
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}

    - name: Run the tests
      run: pipenv run python tests/tests.py
      working-directory: ./app

    - name: Change variables in app.yaml
      run: |
        sh ../deployment_automation/replace_variables.sh app.yaml
      working-directory: ./app
      
    - name: Run deployment
      if: success()
      uses: actions/gcloud/cli@master
      env:
        CLOUDSDK_CORE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      with:
        entrypoint: gcloud
        args: app deploy ./app/app.yaml --quiet



